rm -rf ./angr-management/.git
rm -rf ./cooldict/.git
rm -rf ./idalink/.git
rm -rf ./binaries/.git
rm -rf ./mulpyplexer/.git
rm -rf ./claripy/.git
rm -rf ./pyvex/.git
rm -rf ./archinfo/.git
rm -rf ./cle/.git
rm -rf ./monkeyhex/.git
rm -rf ./simuvex/.git
rm -rf ./ana/.git
rm -rf ./angr/.git
rm -rf ./vex/.git
rm -rf ./superstruct/.git
rm -rf ./angrop/.git
rm -rf ./angr-doc/.git
rm -rf ./angr-management/.gitignore
rm -rf ./cooldict/.gitignore
rm -rf ./idalink/.gitignore
rm -rf ./binaries/.gitignore
rm -rf ./mulpyplexer/.gitignore
rm -rf ./claripy/.gitignore
rm -rf ./pyvex/.gitignore
rm -rf ./archinfo/.gitignore
rm -rf ./cle/.gitignore
rm -rf ./monkeyhex/.gitignore
rm -rf ./simuvex/.gitignore
rm -rf ./ana/.gitignore
rm -rf ./angr/.gitignore
rm -rf ./vex/.gitignore
rm -rf ./superstruct/.gitignore
rm -rf ./angrop/.gitignore
rm -rf ./angr-doc/.gitignore

